### ISSUE TITLE
Suggestion: set index with animation

### ISSUE THREAD

**Issue by jb-5murf** [pavelbabenko/react-native-awesome-gallery#46]
Hi, I like this library very much. One thing I'm missing is possibity to set index with animation. Something like in [react-native-reanimated-carousel](https://github.com/dohooo/react-native-reanimated-carousel/blob/main/docs/props.md). It would be great to have such a feature.

**Comment by lpatrun** [comment]
Change line 963 to 
translateX.value = withTiming(newIndex * -(dimensions.width + emptySpaceWidth)); 
and thats all

**Comment by pavelbabenko** [comment]
Released in [v0.3.6](https://github.com/pavelbabenko/react-native-awesome-gallery/releases/tag/v0.3.6)
