### ISSUE TITLE
react-native-reanimated v3 support

### ISSUE THREAD

**Issue by rosskhanas** [pavelbabenko/react-native-awesome-gallery#51]
Hey, thanks for a great package. Do you plan to support react-native-reanimated v3? Currently, npm install fails because of `^2.x.x` in peer dependencies.

**Comment by pavelbabenko** [comment]
Released in [v0.3.6](https://github.com/pavelbabenko/react-native-awesome-gallery/releases/tag/v0.3.6)

**Comment by rosskhanas** [comment]
@pavelbabenko дякую 🇺🇦
