### ISSUE TITLE
Error: GestureDetector must be used as a descendant of GestureHandlerRootView

### ISSUE THREAD

**Issue by wanghanzhen** [pavelbabenko/react-native-awesome-gallery#55]
Error: GestureDetector must be used as a descendant of GestureHandlerRootView. Otherwise the gestures will not be recognized. See https://docs.swmansion.com/react-native-gesture-handler/docs/installation for more details.

"react-native-gesture-handler": "~2.12.0",

**Comment by pavelbabenko** [comment]
@wanghanzhen You should wrap your app with
`<GestureHandlerRootView style={{flex: 1}}>{...your app}</GestureHandlerRootView>`
