### ISSUE TITLE
Swiping Transition

### ISSUE THREAD

**Issue by turkergercik** [pavelbabenko/react-native-awesome-gallery#56]
Hello, this package is awesome. ı want to add opacity transition while swipe to close. ı tried something but the changes ı made doesn't affect the code. How can ı modify the package code ?

**Comment by pavelbabenko** [comment]
Hi @turkergercik 
I can add a new callback, something like `onSwipeToCloseChange` which will require a worklet, so you can easily use that to manipulate your sharedValue and change the opacity. That will also require wrapping Gallery with your own container

**Comment by turkergercik** [comment]
Thank your for your reply and if this callback return translationY value, ı can check whether the panning started from bottom or top. lastly as an advice swipe to close should be triggerred if scale is equal to 1.

**Comment by pavelbabenko** [comment]
@turkergercik Added `onTranslationYChange(translationY: number, shouldClose: boolean)` callback in [v0.4.1](https://github.com/pavelbabenko/react-native-awesome-gallery/releases/tag/v0.4.1)
