### ISSUE TITLE
Replace 2 loops by one

### ISSUE THREAD

**Issue by mykyta-rusyn** [pavelbabenko/react-native-awesome-gallery#59]
In the `snapPoint` function we have two loops -  that should find the minimum delta. This function looks good, but we can change it to one loop, with the same functionality.
From:
```
const deltas = points.map((p) => Math.abs(point - p));
const minDelta = Math.min.apply(null, deltas);
```
To:
```
let minDelta = Number.MAX_VALUE;
for (let i = 0; i < points.length; i++) {
  const newDelta = Math.abs(point - points[i]);
  if (newDelta < minDelta) {
    minDelta = newDelta;
  }
}
```

**Comment by pavelbabenko** [comment]
@mykyta-rusyn The function doesn't return `minDelta`. It returns a point with minimum delta. If you find a solution which returns point with minimum delta with a single loop, feel free to create a PR
