### ISSUE TITLE
Question: can I get access to current scale without use events?

### ISSUE THREAD

**Issue by dguerreros93** [pavelbabenko/react-native-awesome-gallery#64]
I'm using a renderItem and I added description, but I wanna hide the text when scale is different to 1. 

I'm using `onScaleStart` and `onScaleEnd ` and its working, but when I trigger a doubleTap, I don´t have any way to validate inside this event that the scale is 1 or not.

**Comment by pavelbabenko** [comment]
@dguerreros93 Added params to `onDoubleTap(toScale: number)` and `onScaleStart(scale: number)` in [v0.4.1](https://github.com/pavelbabenko/react-native-awesome-gallery/releases/tag/v0.4.1). Hope that helps!
