### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by arunkumar-pyt** [pavelbabenko/react-native-awesome-gallery#66]
Inside Modal its not working

Please kindly help

**Comment by vasylnahuliak** [comment]
> On Android RNGH does not work by default because modals are not located under React Native Root view in native hierarchy. To fix that, components need to be wrapped with gestureHandlerRootHOC

@arunkumar-pyt If you encounter an issue on Android, you can try this solution
https://docs.swmansion.com/react-native-gesture-handler/docs/fundamentals/installation/#usage-with-modals-on-android

**Comment by pavelbabenko** [comment]
Should be fixed in 0.3.9
