### ISSUE TITLE
[Question] Is it possible to only use lightbox/carousel mode (without list gallery)?

### ISSUE THREAD

**Issue by davide-granello** [pavelbabenko/react-native-awesome-gallery#69]
Hey, i'm considering using this package in my project. I need to display a carousel of images, with swiping left/right and pinching for zooming.
I already have the actual gallery, using [FlashList](https://shopify.github.io/flash-list/) because i need it to be masonry-style.
So i was wondering if i can open the carousel view of this package directly by clicking an item in my masonry gallery.

btw the package seems nice! Good work.

**Comment by pavelbabenko** [comment]
Hi @davide-granello 
Yes, you can create a new screen with this gallery and pass images via params or open a Modal with Gallery rendered
