### ISSUE TITLE
Баг в скролле

### ISSUE THREAD

**Issue by iuan95** [pavelbabenko/react-native-awesome-gallery#74]
Пакет не жб, есть один баг, делаю зум, любой край картинки перетаскиваю до середины экрана, и вот баг

![Screenshot_1715698155](https://github.com/pavelbabenko/react-native-awesome-gallery/assets/68243476/a8a7c2c8-5a8a-461b-b9df-031458dc893c)

**Comment by pavelbabenko** [comment]
@iuan95 Describe your issue in English, please. Also, screen recording would be helpful
