### ISSUE TITLE
[Feature Request] Add Support for High-Resolution Image Loading on zoom

### ISSUE THREAD

**Issue by crank-chips** [pavelbabenko/react-native-awesome-gallery#78]
Hi Pavel! First of all, I want to say a huge thank you for your Awesome Gallery. It's a great package and it really helped me achieve my goal.

I'm not sure if it's possible with the current version, but it would be great to have the ability to initially load an image in low resolution as a thumbnail (e.g., 800x600) and then load it in high resolution once double-tapped or pinch zoomed (e.g., 6400x4800).

Correct me if I'm wrong, but as I understand it, currently it renders the component once. Is it possible to add one more parameter to re-render item on zoom? This would really help to improve performance and reduce traffic usage.

**Comment by pavelbabenko** [comment]
@crank-chips I guess, you can implement that by using custom `renderItem` + callbacks
