### ISSUE TITLE
[Question] - Support video components (expo-av, react-native-video, etc.)

### ISSUE THREAD

**Issue by SelfDestroyer** [pavelbabenko/react-native-awesome-gallery#79]
Hi @pavelbabenko! Thank you for your hard work! I really adore this package. I have a couple of questions for you. Can I use this package for rendering video components? Will there be any performance issues if I use this component for this?

**Comment by pavelbabenko** [comment]
Hi @SelfDestroyer 
I didn't try rendering videos, but I assume that it should work with custom `renderItem`

**Comment by GunnarAK** [comment]
@SelfDestroyer hey, did you succeed in using this with videos?
Thanks in advance!

**Comment by rmmgc** [comment]
I recently needed to add video, it can easily be done with custom render function. Here is an example that is using `react-native-video`

```javascript
function renderItem({ item, setImageDimensions }: RenderItemInfo<Attachment>) {
  if (item.type === 'video') {
    return (
      <View
        style={{
          flex: 1,
          justifyContent: 'center',
          alignContent: 'center',
        }}>
        <Video
          source={{ uri: item.fileUri }}
          style={[
            {
              width: Dimensions.get('screen').width,
              height:
                Dimensions.get('screen').width / (item.width / item.height),
            },
          ]}
          controls
        />
      </View>
    )
  }

  return (
    <Image
      source={{ uri: item.fileUri }}
      style={[StyleSheet.absoluteFillObject]}
      resizeMode="contain"
      onLoad={e => {
        const { width, height } = e.nativeEvent.source
        setImageDimensions({ width, height })
      }}
    />
  )
}
```

**Comment by shuo-hiwintech** [comment]
> 我最近需要添加视频，使用自定义渲染函数可以轻松完成。下面是使用的示例`react-native-video`
> 
> function renderItem({ item, setImageDimensions }: RenderItemInfo<Attachment>) {
>   if (item.type === 'video') {
>     return (
>       <View
>         style={{
>           flex: 1,
>           justifyContent: 'center',
>           alignContent: 'center',
>         }}>
>         <Video
>           source={{ uri: item.fileUri }}
>           style={[
>             {
>               width: Dimensions.get('screen').width,
>               height:
>                 Dimensions.get('screen').width / (item.width / item.height),
>             },
>           ]}
>           controls
>         />
>       </View>
>     )
>   }
> 
>   return (
>     <Image
>       source={{ uri: item.fileUri }}
>       style={[StyleSheet.absoluteFillObject]}
>       resizeMode="contain"
>       onLoad={e => {
>         const { width, height } = e.nativeEvent.source
>         setImageDimensions({ width, height })
>       }}
>     />
>   )
> }

It works but it's very laggy on android QAQ.

**Comment by rmmgc** [comment]
@shuo-hiwintech I also changed my approach. I decided to only show video thumbnail in gallery with Play icon over it. On press, it opens video screen with video controls.

**Comment by shuo-hiwintech** [comment]
> [@shuo-hiwintech](https://github.com/shuo-hiwintech) I also changed my approach. I decided to only show video thumbnail in gallery with Play icon over it. On press, it opens video screen with video controls.

Thanks, nice idea, I'll give it a try.
May I ask how you get the video thumbnails? expo-video-thumbnails ? I feel a bit slow using it QAQ

**Comment by rmmgc** [comment]
> Thanks, nice idea, I'll give it a try. May I ask how you get the video thumbnails? expo-video-thumbnails ? I feel a bit slow using it QAQ

I use `react-native-compressor` for obvious reasons and they also have [util function that can create video thumbnail](https://github.com/numandev1/react-native-compressor?tab=readme-ov-file#video-thumbnail).
