### ISSUE TITLE
Zoom out is breaking the experience

### ISSUE THREAD

**Issue by eladgel** [pavelbabenko/react-native-awesome-gallery#80]
When I try to pinch out the image, the behavior spirals out of control :P.

Attached is a video and my code that is based on the example code:

https://gist.github.com/eladgel/a4cf0ac8063c2ad85ee80ff79de1d7d3

https://github.com/pavelbabenko/react-native-awesome-gallery/assets/412137/a652aaa6-3146-470b-b3a2-f538da300de0

**Comment by jamesedmonston** [comment]
Note that this seems to have been introduced in `0.4.0` (https://github.com/pavelbabenko/react-native-awesome-gallery/commit/74db07f09b493b8a8e44352855f8bdaf87698747).

Downgrading to `0.3.9` fixes the issue.

**Comment by pavelbabenko** [comment]
Fixed in [v0.4.1](https://github.com/pavelbabenko/react-native-awesome-gallery/releases/tag/v0.4.1)

**Comment by jamesedmonston** [comment]
Thanks!
